name: flawless_cli
description: Command-line tools for bootstrapping and managing Flawless UI in Flutter projects.
version: 0.1.0-alpha.6
homepage: https://flawless.codelabmw.dev
repository: https://github.com/flawless-ui/flawless
issue_tracker: https://github.com/flawless-ui/flawless/issues

topics:
  - cli
  - flutter
  - ui
  - design-system
  - tooling

resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  path: ^1.9.0
  args: ^2.4.2
  yaml_edit: ^2.2.2
  pubspec_parse: ^1.3.0

dev_dependencies:
  lints: ^6.1.0
  test: ^1.25.6

executables:
  flawless_cli: flawless_cli
  flawless: flawless_cli