name: flawless_core
description: Core contracts, tokens, and primitives for the Flawless design system.
version: 0.1.0-alpha.6
homepage: https://flawless.codelabmw.dev
repository: https://github.com/flawless-ui/flawless
issue_tracker: https://github.com/flawless-ui/flawless/issues

topics:
  - design-system
  - ui
  - tokens
  - theming
  - dart

resolution: workspace

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
