name: flawless_glass_theme
description: "Glassmorphism design system implementation for Flawless."
version: 0.1.0-alpha.6
homepage: https://flawless.codelabmw.dev
repository: https://github.com/flawless-ui/flawless
issue_tracker: https://github.com/flawless-ui/flawless/issues

topics:
  - flutter
  - ui
  - glassmorphism
  - theming
  - design-system

resolution: workspace

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flawless_core: ^0.1.0-alpha.6
  flawless_theme: ^0.1.0-alpha.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
